name: Docker Image CI

on:
  push:
    paths:
      - 'entrypoint.sh'
      - Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag clang-format-action:$(date +%s)
