name: shellcheck

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'entrypoint.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'entrypoint.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ludeeus/action-shellcheck@1.0.0

