name: shellcheck

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: ludeeus/action-shellcheck@1.0.0

