name: shfmt

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/shfmt.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/shfmt.yml'

jobs:
  format:
    env:
      SHFMT_VERSION: 3.0.1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install shfmt
      run: sudo wget "https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64" -O /usr/local/bin/shfmt

    - name: Check .sh files
      run: shfmt -d .

